// Code generated by jtd-codegen for Go v0.2.1. DO NOT EDIT.

package jtd_codegen_e2e

import (
	"encoding/json"
	"fmt"
)

// A description for discriminator
type RootDiscriminatorWithDescription struct {
	Value IRootDiscriminatorWithDescription `json:"-"`
}

func (v RootDiscriminatorWithDescription) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.Value)
}

func (v *RootDiscriminatorWithDescription) UnmarshalJSON(b []byte) error {
	var t struct { T string `json:"foo"` }
	if err := json.Unmarshal(b, &t); err != nil {
		return err
	}

	var value IRootDiscriminatorWithDescription
	var err error

	switch t.T {
	case "bar":
		var v RootDiscriminatorWithDescriptionBar
		err = json.Unmarshal(b, &v)
		value = v
	default:
		err = fmt.Errorf("RootDiscriminatorWithDescription: bad foo value: %q", t.T)
	}

	if err != nil {
		return err
	}

	v.Value = value
	return nil
}

// IRootDiscriminatorWithDescription is an interface type that RootDiscriminatorWithDescription types implement.
// It can be the following types:
//
// - [RootDiscriminatorWithDescriptionBar] (bar)
//
type IRootDiscriminatorWithDescription interface {
	Foo() string
	isRootDiscriminatorWithDescription()
}

func (RootDiscriminatorWithDescriptionBar) Foo() string { return "bar" }

func (RootDiscriminatorWithDescriptionBar) isRootDiscriminatorWithDescription() {}

func (v RootDiscriminatorWithDescriptionBar) MarshalJSON() ([]byte, error) {
	type Alias RootDiscriminatorWithDescriptionBar
	return json.Marshal(struct {
		T string `json:"foo"`
		Alias
	}{
		v.Foo(),
		Alias(v),
	})
}

func (v *RootDiscriminatorWithDescriptionBar) UnmarshalJSON(b []byte) error {
	type Alias RootDiscriminatorWithDescriptionBar
	var a struct {
		T string `json:"foo"`
		Alias
	}

	if err := json.Unmarshal(b, &a); err != nil {
		return err
	}

	if a.T != "bar" {
		return fmt.Errorf("RootDiscriminatorWithDescriptionBar: bad foo value: %q", a.T)
	}

	*v = RootDiscriminatorWithDescriptionBar(a.Alias)
	return nil
}


// A description for discriminator variant
type RootDiscriminatorWithDescriptionBar struct {
}

// A description for enum
type RootEnumWithDescription string

const (
// A description for X
	RootEnumWithDescriptionX RootEnumWithDescription = "X"

// A description for Y
	RootEnumWithDescriptionY RootEnumWithDescription = "Y"

// A description for Z
	RootEnumWithDescriptionZ RootEnumWithDescription = "Z"
)

// A description for properties
type RootPropertiesWithDescription struct {
}

type Root struct {
	// A description for discriminator
	DiscriminatorWithDescription RootDiscriminatorWithDescription `json:"discriminator_with_description"`

	// A description for enum
	EnumWithDescription RootEnumWithDescription `json:"enum_with_description"`

	// Whereas disregard and contempt for human rights have resulted in barbarous
	// acts which have outraged the conscience of mankind, and the advent of a
	// world in which human beings shall enjoy freedom of speech and belief and
	// freedom from fear and want has been proclaimed as the highest aspiration of
	// the common people,
	LongDescription string `json:"long_description"`

	// A description for properties
	PropertiesWithDescription RootPropertiesWithDescription `json:"properties_with_description"`

	// A description for ref
	RefWithDescription Baz `json:"ref_with_description"`

	// A description for string
	StringWithDescription string `json:"string_with_description"`
}

// A description for a definition
type Baz = string
